on:
  push:
    branches:
      - main

name: release-please

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: iaa-inc-runners
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v3
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          package-name: IAA GH - Runner
          release-type: php
